/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.netthreads.android.bulletml;

public final class R {
    public static final class array {
        /**  bullet_direction 
         */
        public static final int bullet_direction_type=0x7f050000;
        public static final int bullet_direction_values=0x7f050001;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int help_text_font_size=0x7f060002;
        public static final int ml_list_font_size=0x7f060000;
        public static final int ml_list_no_items_font_size=0x7f060001;
        public static final int seekbar_value_font_size=0x7f060003;
    }
    public static final class drawable {
        public static final int ic_menu_help=0x7f020000;
        public static final int ic_menu_info_details=0x7f020001;
        public static final int ic_menu_preferences=0x7f020002;
        public static final int icon_seekbar=0x7f020003;
    }
    public static final class id {
        public static final int app_version=0x7f080001;
        public static final int help_text_view=0x7f080003;
        public static final int link_text_view=0x7f080002;
        public static final int ml_list_show_about=0x7f08000a;
        public static final int ml_list_show_help=0x7f080009;
        public static final int ml_list_show_settings=0x7f080008;
        public static final int name=0x7f080004;
        public static final int seekbar=0x7f080007;
        public static final int seekbar_icon=0x7f080005;
        public static final int seekbar_value=0x7f080006;
        public static final int text=0x7f080000;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int help=0x7f030001;
        public static final int main=0x7f030002;
        public static final int ml_list=0x7f030003;
        public static final int ml_row=0x7f030004;
        public static final int seekbar_dialog=0x7f030005;
    }
    public static final class menu {
        public static final int ml_list_activity_menu=0x7f070000;
    }
    public static final class string {
        public static final int about=0x7f04000a;
        public static final int activity_about=0x7f040007;
        public static final int activity_bullet_ml=0x7f040004;
        public static final int activity_help=0x7f040006;
        public static final int activity_preferences=0x7f040005;
        public static final int app_name=0x7f040002;
        public static final int author_site=0x7f040009;
        public static final int copyright=0x7f040008;
        /**  Shared Preferences 
         */
        public static final int data_preferences=0x7f040010;
        public static final int dialog_ok=0x7f04000d;
        public static final int dialog_title=0x7f04000e;
        public static final int help=0x7f04000c;
        public static final int help_text=0x7f040001;
        public static final int line_thickness=0x7f040012;
        public static final int link_text=0x7f040000;
        public static final int main_no_items=0x7f040003;
        public static final int rank=0x7f040011;
        public static final int settings=0x7f04000b;
        public static final int unknown=0x7f04000f;
    }
}
